🐛  Fixes a bug where 'handleNodeClick' could runtime error if the node had already been removed.
wbkd/react-flow pull request #3294
Opened 2023-08-04 10:35 UTC by hayleigh-dot-dev

Two changes:

- `handleNodeClick` no-ops if the target node doesn't exist.
- A new error is reported:

```js
`Node with id "${id}" does not exist, it may have been removed. This can happen when a node is deleted before the "onNodeClick" handler is called. If this wasn't on purpose, please defer deleting this node until the "onNodeClick" handler is called by using "requestAnimationFrame" or "setTimeout".`
```

This can come up if a custom node has a delete button, for example, and the user _also_ has a `onNodeClick` handler set up on the `<ReactFlow>` component.

2023-08-04 10:38 UTC, hayleigh-dot-dev commented
See https://github.com/wbkd/react-flow-docs/pull/131 for the companion docs update.

2023-08-07 08:33 UTC, moklick commented
I think it's fine when this part ("This can happen when a node is deleted before the "onNodeClick" handler is called. If this wasn't on purpose, please defer deleting this node until the "onNodeClick" handler is called by using "requestAnimationFrame" or "setTimeout".") of the error message can only be found on the troubleshooting page.

2023-08-07 08:34 UTC, moklick requested changes

2023-08-07 08:34 UTC, moklick commented on packages/core/src/contants.ts
> +    `Node with id "${id}" does not exist, it may have been removed. This can happen when a node is deleted before the "onNodeClick" handler is called. If this wasn't on purpose, please defer deleting
"Node with id "${id}" does not exist, it may have been removed." - this is enough for the error message

2023-08-09 09:09 UTC, merged